# THIS SCRIPT IS AUTOGENERATED FROM data/input/02-TestNotebook.ipynb. 


def multiply(x:int, y:int):
    return x*y


def add(x:int, y:int):
    return x+y


def subtract(x:int, y:int):
    # Single line comment
    return x - y
